apiVersion: v1
kind: Service
metadata:
  name: yk-talos-management-metrics
  namespace: yk-talos-management-system
  labels:
    app.kubernetes.io/name: yk-talos-management
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: yk-talos-management
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
