---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: yk-talos-management-manager
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - talos.yuriykovalchuk.dev
  resources:
  - talosclusterbootstraps
  - talosnodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - talos.yuriykovalchuk.dev
  resources:
  - talosclusterbootstraps/status
  - talosclusters/status
  - talosnodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - talos.yuriykovalchuk.dev
  resources:
  - talosclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
